//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidtownRestaurant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidtownRestaurant.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Red wine,8.99
        ///2,White wine,7.99
        ///3,Rose wine,6.99
        ///4,Vodka,5.99
        ///5,Dewars scotch,10.99
        ///6,1800 coconut tequila,9.99
        ///7,Remy cognac,12.99
        ///8,Jim beam bourbon,15.99
        ///9,Margarita,13.99
        ///10,Punch,7.99
        ///11,Long island,15.99
        ///12,Bloody mary,12.99
        ///13,Black tea,2.5
        ///14,Fruit tea,2.9
        ///15,Water,1
        ///16,Sparkling water,1.99
        ///17,Orange juice,2.99.
        /// </summary>
        public static string drinks {
            get {
                return ResourceManager.GetString("drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Nachos,5.99
        ///2,Onion Rings,4.99
        ///3,Mozarella sticks,8.99
        ///4,Chicken salads,10.5
        ///5,Shrimp salads,12.99
        ///6,Cheese burger,15.1
        ///7,Fish burger,11.3
        ///8,Mexican Burger,15.99
        ///9,Rib eye steak,25.99
        ///10,T-bone steak,23.99
        ///11,Bbq pork chops,22.7
        ///12,Beef kebab,29.7
        ///13,Grill shrimp,15.99
        ///14,Grill salmon,17.99.
        /// </summary>
        public static string food {
            get {
                return ResourceManager.GetString("food", resourceCulture);
            }
        }
    }
}
